<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="mikrorobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="10" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.3" />
  <xacro:property name="depth" value="0.5" /> 
  <xacro:property name="height" value="0.17" />
  <xacro:property name="wheel_mass" value="1.5" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_width" value="0.07" />
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="wheel_offset_x" value="0.2" /> <!-- Wheel offset depth-direction -->
  <xacro:property name="wheel_offset_y" value="0.2" /> <!-- Wheel offset width-direction -->
  <xacro:property name="wheel_offset_z" value="${-height/2 + 0.05}" /> <!-- Wheel offset height-direction -->
  

    <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${depth} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${depth} ${width} ${height}"/>
      </geometry>
      <material name="yellow">
        <color rgba="0.8 0.8 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="${depth/2} ${width/2} ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + depth*depth)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height*height + depth*depth)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + height*height)}"/>
    </inertial>
  </link>

  <!-- Front Right Wheel -->
  <joint name="joint_f_r_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="f_r_wheel"/>
    <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>  
  
  <link name="f_r_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="black">
        <color rgba="0.05 0.05 0.05 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0"/>
      <inertia ixx="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               ixy="0"
               ixz="0"
               iyy="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               iyz="0"
               izz="${wheel_mass * wheel_radius * wheel_radius / 2.0}" />
    </inertial>    
  </link>

  <!-- Back Right Wheel -->
  <joint name="joint_b_r_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="b_r_wheel"/>
    <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>  
  
  <link name="b_r_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0"/>
      <inertia ixx="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               ixy="0"
               ixz="0"
               iyy="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               iyz="0"
               izz="${wheel_mass * wheel_radius * wheel_radius / 2.0}" />
    </inertial>  
  </link>
  
  <!-- Front Left Wheel -->
  <joint name="joint_f_l_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="f_l_wheel"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>  
  
  <link name="f_l_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0"/>
      <inertia ixx="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               ixy="0"
               ixz="0"
               iyy="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               iyz="0"
               izz="${wheel_mass * wheel_radius * wheel_radius / 2.0}" />
    </inertial>  
  </link>

    <!-- Back Left Wheel -->
  <joint name="joint_b_l_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="b_l_wheel"/>
     <origin xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>  
  
  <link name="b_l_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="black"/>
    </visual>

        <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0"/>
      <inertia ixx="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               ixy="0"
               ixz="0"
               iyy="${wheel_mass / 12.0*3* (wheel_radius * wheel_radius + wheel_width * wheel_width)}"
               iyz="0"
               izz="${wheel_mass * wheel_radius * wheel_radius / 2.0}" />
    </inertial>  
  </link>

    <!-- Camera -->
  <link name="camera">
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<cylinder length="0.03" radius ="0.02"/>
      </geometry>
    </collision>
    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <cylinder length="0.03" radius="0.02" />
      </geometry>
      <material name="black"/>
    </visual>
    
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="${depth/2 - 0.05} 0 ${height/2}" rpy="-1.570795 0 -1.570795" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>

  <transmission name="tran_f_r">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_f_r_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_f_r">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_b_r">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_b_r_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_b_r">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <transmission name="tran_f_l">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_f_l_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_f_l">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran_b_l">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_b_l_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_b_l">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
</robot>
